// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Ac4ghaEemF-s9pqJT71-5YDpLMS1qAM',
    appId: '1:210911877973:web:d8acd70da34a14fa1beddc',
    messagingSenderId: '210911877973',
    projectId: 'portones-mym',
    authDomain: 'portones-mym.firebaseapp.com',
    storageBucket: 'portones-mym.firebasestorage.app',
    measurementId: 'G-CBDJ67FVSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8gPkBGOa0DTQJ8Gext5RNTS-lpOZKeTU',
    appId: '1:210911877973:android:315323142b5c8aa21beddc',
    messagingSenderId: '210911877973',
    projectId: 'portones-mym',
    storageBucket: 'portones-mym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1zxmP4o29r7qm-dyT-70BbW-QE1oB4hg',
    appId: '1:210911877973:ios:fec7f8c09c3060b31beddc',
    messagingSenderId: '210911877973',
    projectId: 'portones-mym',
    storageBucket: 'portones-mym.firebasestorage.app',
    iosBundleId: 'com.example.portonesMym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1zxmP4o29r7qm-dyT-70BbW-QE1oB4hg',
    appId: '1:210911877973:ios:fec7f8c09c3060b31beddc',
    messagingSenderId: '210911877973',
    projectId: 'portones-mym',
    storageBucket: 'portones-mym.firebasestorage.app',
    iosBundleId: 'com.example.portonesMym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Ac4ghaEemF-s9pqJT71-5YDpLMS1qAM',
    appId: '1:210911877973:web:1675d4753d8af5981beddc',
    messagingSenderId: '210911877973',
    projectId: 'portones-mym',
    authDomain: 'portones-mym.firebaseapp.com',
    storageBucket: 'portones-mym.firebasestorage.app',
    measurementId: 'G-RHDHV39CCS',
  );
}
